#!/usr/bin/env bash

set -e

sudo apt-get install -y libappindicator3-1 linux-headers-`uname -r` gcc make

cd /tmp/
wget -O droidcam_latest.zip https://files.dev47apps.net/linux/droidcam_2.1.3.zip
unzip droidcam_latest.zip -d droidcam
cd droidcam
sudo ./install-client
sudo ./install-video
