#!/usr/bin/env bash

ln -sf $PWD/.gitconfig $HOME/.gitconfig
ln -sf $PWD/.gitconfig_personal $HOME/.gitconfig_personal

# This copy is done on purpose, because I don't want to leak my work email
cp $PWD/.gitconfig_work $HOME/.gitconfig_work

echo "Please modify email in .gitconfig_work file"

