#!/usr/bin/env bash

# Commits are signed with this key, so it must exist or every commit fails
if [ ! -f "$HOME/.ssh/id_ed25519.pub" ]; then
    ssh-keygen -t ed25519 -N "" -f "$HOME/.ssh/id_ed25519"
    echo "Add ~/.ssh/id_ed25519.pub to GitHub as a *signing* key"
fi

ln -sf $PWD/.gitconfig $HOME/.gitconfig

# This copy is done on purpose, because I don't want to leak my work email
cp $PWD/.gitconfig_work $HOME/.gitconfig_work

echo "Please modify email in .gitconfig_work file"

# Install git-lfs
GIT_LFS_VERSION=3.7.1
wget -q https://github.com/git-lfs/git-lfs/releases/download/v$GIT_LFS_VERSION/git-lfs-linux-amd64-v$GIT_LFS_VERSION.tar.gz
tar -xf git-lfs-linux-amd64-v$GIT_LFS_VERSION.tar.gz
sudo ./git-lfs-$GIT_LFS_VERSION/install.sh
rm -rf git-lfs-$GIT_LFS_VERSION git-lfs-linux-amd64-v$GIT_LFS_VERSION.tar.gz
