#!/bin/sh

# Install dependencies
# jq - JSON processor
sudo apt update && sudo apt install -y \
    jq \
    g++ \
    python3-venv \
    python3-pip \
    npm \
    htop \
    xclip \
    clang \
    kazam \
    imagemagick
