#!/bin/sh

set -e

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.config
mkdir -p $HOME/work
mkdir -p $HOME/personal


echo "PATH=$PATH:~/.local/bin" >> ~/.bashrc

./install_dependencies

for i in bash git terminal tmux i3 neovim; do
    echo "$PWD/$i"
    cd $i && ./setup
    cd ..
done

# There is issue with brightnessctl for new Ubuntu:
# https://github.com/Hummer12007/brightnessctl/issues/63#issuecomment-921753747
sudo usermod -aG video ${USER}

echo "Please reboot"

