#!/usr/bin/env bash

set -e

mkdir -p $HOME/.local/bin
mkdir -p $HOME/.config
mkdir -p $HOME/work
mkdir -p $HOME/personal

./install_dependencies

# There is issue with brightnessctl for new Ubuntu:
# https://github.com/Hummer12007/brightnessctl/issues/63#issuecomment-921753747
sudo usermod -aG video ${USER}

echo "Please reboot"

