#!/usr/bin/env bash

sudo ln -sf $PWD/powermode /usr/local/bin/powermode

sudo cp $PWD/powermode-restore.service /etc/systemd/system/.
sudo systemctl daemon-reload
sudo systemctl enable powermode-restore.service
