#!/usr/bin/env bash

# playerctl - media controls (pause, play, next, previous)
# brightnessctl - screen brightness control
sudo apt-get install -y \
    i3 \
    i3lock \
    feh \
    ripgrep \
    brightnessctl \
    playerctl \
    gnome-screenshot \
    dunst

sudo apt-get install -y python3-i3ipc python3-pynput

mkdir -p $HOME/.config/i3
mkdir -p $HOME/.local/share/backgrounds

ln -sf $PWD/config $HOME/.config/i3/config
ln -sf $PWD/i3status.conf $HOME/.config/i3/i3status.conf
# ln -sf $PWD/i3unityfix.py $HOME/.local/bin/i3unityfix
# ln -sf $PWD/i3_pomodoro.py $HOME/.local/bin/i3_pomodoro
ln -sf $PWD/lock-screen $HOME/.local/bin/lock-screen

# Investigate some sweet dmenu options to make screenshots and recordings:
# https://github.com/yschaeff/sway_screenshots/blob/master/screenshot.sh
