#!/bin/sh

# maim - screenshots
# playerctl - media controls (pause, play, next, previous)
# brightnessctl - screen brightness control
sudo apt update && sudo apt install -y \
    i3 \
    feh \
    fzf \
    ripgrep \
    brightnessctl \
    maim \
    playerctl \
    rofi \
    gnome-screenshot

pip3 install i3ipc pynput

mkdir -p $HOME/.config/i3
ln -sf "$PWD/config" "$HOME/.config/i3/config"
ln -sf "$PWD/i3unityfix.py" "$HOME/.local/bin/i3unityfix.py"

# Investigate some sweet dmenu options to make screenshots and recordings:
# https://github.com/yschaeff/sway_screenshots/blob/master/screenshot.sh
