#!/usr/bin/env bash

mkdir -p $HOME/.local/share/backgrounds

shopt -s nullglob
for image in "$PWD"/*.{jpg,jpeg,png,webp,bmp,gif}; do
  ln -sf "$image" "$HOME/.local/share/backgrounds/$(basename "$image")"
done
