#!/usr/bin/env bash

mkdir -p $HOME/.local/share/backgrounds

ln -sf $PWD/tim-mccartney-39907.jpg $HOME/.local/share/backgrounds/tim-mccartney-39907.jpg
ln -sf $PWD/prison_mike.jpg $HOME/.local/share/backgrounds/prison_mike.jpg
