#!/usr/bin/env bash

mkdir -p $HOME/.config/systemd/user

rm -rf pomodoro
git clone git@github.com:styczen/pomodoro.git
pushd pomodoro
ln -sf $PWD/pomodoro.py $HOME/.local/bin/pomodoro
ln -sf $PWD/systemd/pomodoro.service $HOME/.config/systemd/user/pomodoro.service
popd
systemctl --user daemon-reload
systemctl --user restart pomodoro.service
systemctl --user enable pomodoro.service
