#!/bin/sh

sudo apt-get install -y \
    tmux \
    fzf

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

ln -sf $PWD/.tmux.conf $HOME/.tmux.conf
ln -sf $PWD/tmux-sessionizer $HOME/.local/bin/tms

