#!/bin/sh

test type tmux >/dev/null 2>&1 && echo "TMUX isn't installed. Skipping." && exit 1

sudo apt install -y fzf

ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
ln -sf "$PWD/tmux-sessionizer" "$HOME/.local/bin/tms"

