#!/usr/bin/env bash

# Setup python-lsp-black
echo "Installing python-lsp-black plugin for Python LSP"
echo "Sourcing Python LSP venv..."
source $HOME/.local/share/nvim/mason/packages/python-lsp-server/venv/bin/activate
echo "Installing plugin..."
pip install python-lsp-black
