#!/usr/bin/env bash

set -e

echo "Sourcing Python LSP venv..."
source $HOME/.local/share/nvim/mason/packages/python-lsp-server/venv/bin/activate

echo "Installing python-lsp-black plugin for Python LSP"
pip install python-lsp-black

echo "Installing python-lsp-ruff plugin for Python LSP"
pip install python-lsp-ruff
