#!/usr/bin/env bash

if command -v nvim >/dev/null 2>&1; then
    echo "Neovim (nvim) is already installed. Skipping setup."
    exit 0
fi

sudo apt-get update && sudo apt-get install -y \
    make \
    gcc \
    ripgrep \
    unzip \
    git \
    xclip

# Install Neovim release version
echo "Installing Neovim"
wget -q https://github.com/neovim/neovim/releases/download/v0.11.1/nvim-linux-x86_64.appimage
chmod +x nvim-linux-x86_64.appimage
sudo mv nvim-linux-x86_64.appimage /usr/local/bin/nvim

echo "Linking NVIM configuration directory..."
ln -sf $PWD/nvim $HOME/.config/nvim

echo "Neovim requires a NERD font for icons, run ../fonts/setup to install one"
