#!/usr/bin/env bash

# Install Neovim release version
echo "Installing Neovim"
rm -rf $HOME/.local/bin/nvim
wget -q https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
chmod u+x nvim.appimage
mv nvim.appimage $HOME/.local/bin/nvim

# Install tree-sitter CLI (currently needed to generate LaTeX grammar)
echo "Installing tree-sitter CLI"
rm -rf $HOME/.local/bin/tree-sitter
wget -q https://github.com/tree-sitter/tree-sitter/releases/download/v0.22.6/tree-sitter-linux-x64.gz
gzip -d tree-sitter-linux-x64.gz
chmod u+x tree-sitter-linux-x64
mv tree-sitter-linux-x64 $HOME/.local/bin/tree-sitter

# Setup fonts
echo "Setting up NERD fonts"
FONTS_PATH=$HOME/.local/share/fonts
mkdir -p $FONTS_PATH
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/3270.zip
unzip -d $FONTS_PATH -q 3270.zip
rm 3270.zip
fc-cache -f

echo "Linking NVIM configuration directory..."
ln -s $PWD/nvim $HOME/.config/nvim

# Setup python-lsp-black
echo "Installing python-lsp-black plugin for Python LSP"
echo "Sourcing Python LSP venv..."
source $HOME/.local/share/nvim/mason/packages/python-lsp-server/venv/bin/activate
echo "Installing plugin..."
pip install python-lsp-black

echo "Please restart terminal"
