#!/usr/bin/env bash

rm -f $HOME/.bashrc
rm -f $HOME/.bash_profile
rm -f $HOME/.profile
rm -f $HOME/.bash_aliases
rm -f $HOME/.bash_exports
rm -f $HOME/.bash_functions

ln -sf $PWD/.bashrc $HOME/.bashrc
ln -sf $PWD/.bash_profile $HOME/.bash_profile
